package org.example.GUIComponents;

import org.example.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainScreen {

    User user;
    ManageDeck manageDeck;
    private JPanel root;
    private JTabbedPane tabbedPane1;
    private JPanel logoutP;
    private JPanel cartP;
    private JPanel personalP;
    private JButton logOutButton;

    public MainScreen(User user) {
        this.user = user;
        JPanel searchDeck = new SearchDeck(user.getType(), this).getRoot();
        tabbedPane1.insertTab("Search", null, searchDeck, "", 1);

        if (user.getType().equals("Manager")) {
            manageDeck = new ManageDeck();
            JPanel manageP = manageDeck.getRoot();
            tabbedPane1.insertTab("Manage", null, manageP, "", 0);
        }
        logOutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int debug = 12;
                ((AppFrame) root.getTopLevelAncestor()).logout();
            }
        });
    }

    public void goToUpdateBook(int isbn)
    {
        tabbedPane1.setSelectedIndex(0);
        manageDeck.goToUpdateBook(isbn);
    }
    public JPanel getRoot() {
        return root;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        tabbedPane1 = new JTabbedPane();
        root.add(tabbedPane1, BorderLayout.CENTER);
        personalP = new JPanel();
        personalP.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Personal", personalP);
        cartP = new JPanel();
        cartP.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Cart", cartP);
        logoutP = new JPanel();
        logoutP.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        tabbedPane1.addTab("Log out", logoutP);
        logOutButton = new JButton();
        logOutButton.setText("Log out");
        logoutP.add(logOutButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

    }
}

